name: smooth_app
description: The next generation of the Open Food Facts mobile apps.
version: 0.0.0+734
publish_to: "none"

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  async: 2.13.0
  go_router: 16.1.0
  barcode_widget: 2.0.4
  carousel_slider: 5.1.1
  cupertino_icons: 1.0.8
  flutter_svg: 2.2.0
  flutter_map: 8.2.1
  html: 0.15.6
  flutter_widget_from_html_core: 0.17.0
  flutter_secure_storage: 9.2.4
  hive: 2.2.3
  hive_flutter: 1.1.0
  http: 1.5.0
  http_parser: 4.1.2
  image_picker: 1.1.2
  l10n_countries: 1.2.0
  latlong2: 0.9.1
  matomo_tracker: 6.0.0
  package_info_plus: 8.3.1
  device_info_plus: 11.5.0
  permission_handler: 12.0.1
  photo_view: 0.15.0
  uuid: 4.5.1
  provider: 6.1.5
  sentry_flutter: 9.6.0
  sqflite: 2.4.2
  sqflite_common_ffi: 2.3.6
  url_launcher: 6.3.2
  visibility_detector: 0.4.0+2
  app_settings: 6.1.1
  diacritic: 0.1.6
  app_store_shared:
    path: ../app_store/shared
  audioplayers: 6.5.0
  flutter_email_sender: 7.0.0
  flutter_native_splash: 2.4.6
  image: 4.5.4
  auto_size_text: 3.0.0
  crop_image: 1.0.16
  shared_preferences: 2.5.3
  intl: 0.20.2
  collection: 1.19.1
  path: 1.9.1
  path_provider: 2.1.5
  share_plus: 11.0.0
  fimber: 0.7.0
  shimmer: ^3.0.0
  rive: 0.13.20
  webview_flutter: 4.13.0
  webview_flutter_android: 4.8.2
  webview_flutter_wkwebview: 3.23.0
  flutter_custom_tabs: 2.4.0
  flutter_image_compress: 2.4.0
  connectivity_plus: 6.1.5
  dart_ping: 9.0.1
  dart_ping_ios: 4.0.2
  flutter_animation_progress_bar: 2.3.1
  email_validator: 3.0.0
  sliver_tools: 0.2.12
  cached_network_image: 3.4.1
  file_picker: 10.3.1
  animated_line_through: 1.0.5
  mobkit_dashed_border: 0.0.8

  # According to the build variant, only one "app store" implementation must be added when building a release
  # Call "flutter pub remove xxxx" to remove unused dependencies
  app_store_apple_store:
    path: ../app_store/apple_app_store

  app_store_google_play:
    path: ../app_store/google_play

  app_store_uri:
    path: ../app_store/uri_store

  # We use two different scanning engines, 
  # mobile scanner powered by ML Kit for the Play Store and Apple App Store,
  # but qr_code_scanner which uses the open source ZXing for F-Droid
  camera: 0.11.2
  
  scanner_shared:
    path: ../scanner/shared

  scanner_ml_kit:
    path: ../scanner/ml_kit

  scanner_zxing:
    path: ../scanner/zxing


  openfoodfacts: 3.24.0
  # openfoodfacts:
  #   path: ../../../openfoodfacts-dart

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: 5.5.0
  path_provider_platform_interface: 2.1.2
  plugin_platform_interface: 2.1.8
  flutter_lints: 6.0.0
  openfoodfacts_flutter_lints:
    git: https://github.com/openfoodfacts/openfoodfacts_flutter_lints.git

# 'flutter pub run flutter_native_splash:create' to update
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#333333"
  #It must be a png file and should be sized for 4x pixel density.
  image: "assets/app/release_icon_transparent_1152x1152.png"

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. Currently, it is only supported for Android < v12 and iOS.
  # 200dp width and 80dp height.
  branding: assets/app/splashscreen_branding.png
  branding_dark: assets/app/splashscreen_branding_dark.png

  # https://developer.android.com/guide/topics/ui/splash-screen
  android_12:
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: "assets/app/release_icon_transparent_70pct_1152x1152.png"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#333333"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/app/
    - assets/audio/
    - assets/cache/
    - assets/cacheTintable/
    - assets/metadata/
    - assets/misc/
    - assets/network/cert.pem
    - assets/onboarding/
    - assets/packagings/
    - assets/preferences/
    - assets/product/
    - assets/icons/

  # /!\
  # Don't use icons SVGs (in assets/fonts/icons), but add them to the font
  # cf (assets/fonts/icons/README.md)

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: SmoothIcons
      fonts:
        - asset: assets/fonts/SmoothIcons.ttf

    - family: FoodIcons
      fonts:
        - asset: assets/fonts/FoodIcons.ttf